protected/controllers/UserController.php
<?php

class UserController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    public $user_id;

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'admin', 'view', 'create', 'update', 'delete', 'contact'),
                'expression' => 'Yii::app()->user->isAdmin()',
            ),
            array('deny', // deny all users
                'actions' => array('admin', 'create', 'delete', 'index', 'view'),
                'expression' => '!Yii::app()->user->isAdmin()'
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
//        $this->layout='//layouts/theme_column2';
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    
    public function getRoles(){
        return array(
            1 => 'Admin',
            2 => 'Docent',
            3 => 'Student'
        );
    }
    
    public function generatePassword() {
        $password = '';
        $characters = '0123456789aAbBcCdDeEfFgGhHiIjJkKlLmMnNOpPqQrRsStTuUvVwWXyYzZ';
        for ($p = 0; $p < 8; $p++) {
            $password .= $characters[mt_rand(0, strlen($characters) - 1)];
        }
        return $password;
    }
    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new User;
        // Uncomment the following line if AJAX validation is needed 
        // $this->performAjaxValidation($model);


        if (isset($_FILES['import_list']) && $_FILES['import_list']['error'] == UPLOAD_ERR_OK) {
            
            if (pathinfo($_FILES['import_list']['name'], PATHINFO_EXTENSION) !== 'csv') {
                $model->addError('wrong_mime_type', "The download file must be \".csv\"");
                $this->render('create', array(
                    'model' => $model,
                    'roles' => $this->getRoles()
                ));
                Yii::app()->end();
            }
            if ($_FILES['import_list']['name'] != ('Docents Email.csv' || 'Students Email.csv')) {
                $model->addError('wrong_file_name', "The download file name must be \"Docents Email\" or \"Students Email\"");
                $this->render('create', array(
                    'model' => $model,
                    'roles' => $this->getRoles()
                ));
                Yii::app()->end();
            }

            switch ($_FILES['import_list']['name']) {
                case 'Docents Email.csv':
                    $user_role = 2;
                    break;
                case 'Students Email.csv':
                default:
                    $user_role = 3;
                    break;
            }
            
            $handle = fopen($_FILES['import_list']['tmp_name'], 'r');
            while (($data = fgetcsv($handle, 1000, ";")) !== FALSE) {
//                echo "<pre>";
//                    print_r($data);
//                echo "</pre>";
//                continue;
                if (!$data[0] || !filter_var($data[0], FILTER_VALIDATE_EMAIL)) {
                    continue;
                }
                if (User::model()->findByAttributes(array('email' => $data[0]))) {
                    continue;
                }
                
                $model->id = false;
                $model->isNewRecord = true;
                $data[0] = trim($data[0]);
                $model->email = $data[0];
                $model->role = $user_role;
                $model->username = explode('@', $model->email);
                $model->username = $model->username[0];
                $password = $this->generatePassword();
                $model->password = md5($password);

                if ($model->save(false)) {
                    $mail = new YiiMailer();
                    $mail->clearLayout(); //if layout is already set in config
                    $mail->setFrom('unasat@unasat.org', 'UNASAT');
                    $mail->setTo($model->email);
                    $mail->setSubject('Succesvolle Registratie UNASAT OFSS');
                    $mail->setBody('Beste gebruiker, <br /><br /> Hierbij ontvangt u de inlog gegevens voor het UNASAT OFSS. <br /> <b>Login Email Address:</b> ' . $model->email . ' <br /> <b>Password:</b> ' . $password . ' <br /> Het UNASAT OFSS kunt u bezoeken via deze link: <a href="http://www.unasat.org/inlogofss.html">http://www.unasat.org/inlogofss.html</a><br /><br /> Mvg, <br /><br /> Het UNASAT Team!');
                    $mail->send();
                }
            }
//            exit;
            $this->redirect(array('user/admin'));
        }



        if (isset($_POST['User'])) {

            $model->attributes = $_POST['User'];
            $model->username = explode('@', $model->email);
            $model->username = $model->username[0];
            $password = $this->generatePassword();
            $model->password = md5($password);
            if ($model->save()) {
                
                $mail = new YiiMailer();
                $mail->setView('registration');
                $mail->setData(array(
                        'from' => 'UNASAT admin.secr@unasat.sr',
                        'to' => $model->email,
                        'subject' => 'Succesvolle Registratie UNASAT OFSS',
                        'email' => $model->email,
                        'password' => $password
                    ));
                $mail->setLayout('mail');
                $mail->setFrom('unasat@unasat.org', 'UNASAT');
                $mail->setTo($model->email);
                $mail->setSubject('Succesvolle Registratie UNASAT OFSS');
                $mail->send();
                
                $this->redirect(array('view', 'id' => $model->id));
            }
        }
        $this->render('create', array(
            'model' => $model,
            'roles' => $this->getRoles()
        ));
    }
    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
//        $this->layout = '//layouts/theme_column2';
        $model = $this->loadModel($id);

        $this->user_id = Yii::app()->user->getId();
        if($this->user_id == 1 || $this->user_id == 136 || $this->user_id == 148 ){
            if (isset($_POST['User'])) {
                $model->attributes = $_POST['User'];

                if ($model->validate()){

                    if (!empty($model->password)){
                        $password = '<b>Password:</b> '.$model->password;
                        $model->password = User::hashPassword($model->password);
                    }else{
                        $password = 'Use old password';
                        unset($model->password);
                    }

                    if($model->save(false));{
                        $mail = new YiiMailer();
                        $mail->clearLayout();//if layout is already set in config
                        $mail->setFrom('unasat@unasat.org', 'UNASAT');
                        $mail->setTo($model->email);
                        $mail->setSubject('Succesvolle Update UNASAT OFSS');
                        $mail->setBody('Beste gebruiker, <br /><br /> Hierbij ontvangt u de herziene inlog gegevens voor het UNASAT OFSS. <br /> <b>Login Email Address:</b> '.$model->email.'<br />'.$password.'<br /><br /> Mvg, <br /><br /> Het UNASAT Team!');
                        $mail->send();
                        Yii::app()->user->setFlash('success', 'Profile has been updated!');
                        $this->redirect(array('update', 'id' => $model->id));
                    }
                }
            }
            $model->password = '';
            $model->new_password = '';
            $this->render('update', array(
                'model' => $model,
                'roles' => $this->getRoles()
            ));

        } else if($this->user_id == NULL || $this->user_id != $id) {
            $this->redirect(Yii::app()->homeUrl);
        }

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
//        if (isset($_POST['User'])) {
//            $model->attributes = $_POST['User'];
//
//            if ($model->validate()){
//
//                 if (!empty($model->password)){
//                    $password = '<b>Password:</b> '.$model->password;
//                    $model->password = User::hashPassword($model->password);
//                 }else{
//                     $password = 'Use old password';
//                     unset($model->password);
//                 }
//
//                if($model->save(false));{
//                    $mail = new YiiMailer();
//                    $mail->clearLayout();//if layout is already set in config
//                    $mail->setFrom('unasat@unasat.org', 'UNASAT');
//                    $mail->setTo($model->email);
//                    $mail->setSubject('Succesvolle Update UNASAT OFSS');

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/filemanager.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/thememain'); ?>
<!--<div id="content">-->
	<?php echo $content; ?>
<!--</div>-->
<?php $this->endContent(); ?>

protected/views/layouts/login.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UNASAT OFSS| Login</title>
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/animate.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/style.css" rel="stylesheet">
</head>
<body class="gray-bg">
 
	<?php echo $content; ?>
    <!-- Mainly scripts -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/jquery-2.1.1.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/bootstrap.min.js"></script>
</body>
</html>

protected/views/layouts/mail.php
<?php echo $content; ?>

protected/views/layouts/main.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>  
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/plugins/dropzone/basic.css" rel="stylesheet">
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/plugins/dropzone/dropzone.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/font-awesome/css/font-awesome.css" rel="stylesheet">
     <!-- Data Tables -->
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/plugins/blueimp/css/blueimp-gallery.min.css" rel="stylesheet">
	<link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/animate.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/css/style.css" rel="stylesheet">
	
	
	<link href="<?php echo Yii::app()->baseUrl; ?>/jstree/themes/default/style.min.css" rel="stylesheet" />
	<link href="<?php echo Yii::app()->baseUrl; ?>/jstree/themes/default/custom.css" rel="stylesheet" /> 
	<!-- Mainly scripts -->
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/jquery-2.1.1.js"></script>
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/bootstrap.min.js"></script>
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/metisMenu/jquery.metisMenu.js"></script>
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
	<!-- Data Tables -->
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/dataTables/dataTables.tableTools.min.js"></script>
	<!-- Custom and plugin javascript -->
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/inspinia.js"></script>
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/pace/pace.min.js"></script>
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/jquery.form.js"></script> 
	
	    <!-- Page-Level Scripts -->
		<!-- dropzone -->
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/dropzone/dropzone.js"></script>	
	 <!-- blueimp gallery -->
	 
	 
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/layout_data/js/plugins/blueimp/jquery.blueimp-gallery.min.js"></script>
	<script>
	$(document).ready(function(){
		$('#page-wrapper').css('min-height', $(window).height());
	});
	</script>

	<style>
		body.DTTT_Print {
			background: #fff;

		}
		.DTTT_Print #page-wrapper {
			margin: 0;
			background:#fff;
		}

		button.DTTT_button, div.DTTT_button, a.DTTT_button {
			border: 1px solid #e7eaec;
			background: #fff;
			color: #676a6c;
			box-shadow: none;
			padding: 6px 8px;
		}
		button.DTTT_button:hover, div.DTTT_button:hover, a.DTTT_button:hover {
			border: 1px solid #d2d2d2;
			background: #fff;
			color: #676a6c;
			box-shadow: none;
			padding: 6px 8px;
		}

		.dataTables_filter label {
			margin-right: 5px;

		}
	</style>
</head>
<body>
<div id="blueimp-gallery" class="blueimp-gallery">
	<div class="slides"></div>
	<h3 class="title"></h3>
	
	<a class="close">×</a>
	
	
</div>
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element"> <span>
						<a data-toggle="dropdown" class="dropdown-toggle" href="#">
							<span class="clear">
								<span class="block m-t-xs"> 
									<strong style="word-wrap:break-word;" class="font-bold"><?php echo isset(Yii::app()->user->email)?Yii::app()->user->email:'';; ?></strong>
								</span>
								<span class="text-muted text-xs block">
									<?php if(Yii::app()->user->isDocent()){ ?>
										Docent
									<?php }elseif(Yii::app()->user->isStudent()){ ?>
										Student
									<?php }elseif(Yii::app()->user->isAdmin()){ ?>
										Admin
									<?php } ?>
								<!--	<b class="caret"></b> -->
								</span> 
							</span>
						 </a>
					</div>
				</li>

							
							<?php $baseUrl = Yii::app()->baseUrl; if(!Yii::app()->user->isGuest){ ?>
							 <li>
                                    <a href="<?php echo Yii::app()->baseUrl; ?>" title="">
                                      <!--  <img class="svg" alt="" src="<?php echo $baseUrl?>/images/personal.svg" /> -->
									  <i class="fa fa-diamond"></i>
                                       <span class="nav-label">Home</span> 
                                    </a>
                             </li>
							
							
							 <li>
                                    <a href="<?php echo $this->createUrl('user/update', array('id' => Yii::app()->user->id)); ?>" title="">
                                      <!--  <img class="svg" alt="" src="<?php echo $baseUrl?>/images/personal.svg" /> -->
									  <i class="fa fa-user-md"></i>
                                       <span class="nav-label">Profile</span> 
                                    </a>
                             </li>
							 
							 <?php } ?>
							<?php $baseUrl = Yii::app()->baseUrl; if(Yii::app()->user->isAdmin()) { ?>	
                                <li>
                                    <a href="<?php echo $this->createUrl('user/admin'); ?>" title="">
                                      <!--  <img class="svg" alt="" src="<?php echo $baseUrl?>/images/users.svg" />   -->
										<i class="fa fa-users"></i>
                                        <span class="nav-label">Users</span> 
                                    </a>
                                </li>
								<?php } ?>
 <!--                               <li>
                                    <a id="logout" href="<?php echo $this->createUrl('site/logout'); ?>">
                                        <img class="svg" alt="" src="<?php echo $baseUrl?>/images/logout.svg" />
                                        LogOut
                                    </a>
                                </li>
-->								
					
					
                    
                    <div class="logo-element">
                        ICT
                    </div>
                <!--<li class="active">
                    <a href="index.html"><i class="fa fa-th-large"></i> <span class="nav-label">Main view</span></a>
                </li>
                <li>
                    <a href="minor.html"><i class="fa fa-th-large"></i> <span class="nav-label">Minor view</span> </a>
                </li>-->
            </ul>
        </div>
	</nav>
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
			<?php if(!Yii::app()->user->isGuest){ ?>
            <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
               <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
             	   <div role="search" class="navbar-form-custom" >
                        <div class="form-group">
                            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                        </div>
                    </div>
				</div>
				<ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="<?php echo $this->createUrl('site/logout'); ?>">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                </ul>
			</nav>
			<?php } ?>
        </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="m-t-lg">
                       <?php echo $content; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
			<?php 
			
               $controller = Yii::app()->getController();
               $isHome = $controller->getId() === 'site' && $controller->getAction()->getId() === 'index';
           ?>
               	 <?php if (!Yii::app()->user->isAdmin() && !Yii::app()->user->isGuest && $isHome) { ?>
					<div class="pull-right">
						<span class="uploadded-size"><?php echo $this->uploadded_size ?>MB</span> of <strong><?php echo $this->upload_size_of ?>MB</strong> Free.
					</div>
				<?php } ?>	
            <div>
                <strong>Copyright</strong> UNASAT &copy; <?php echo date('Y'); ?>
            </div>
        </div>
    </div>
</div>

</body>
</html>

protected/views/layouts/theme_column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/thememain'); ?>
<div id="content">
	<?php echo $content; ?>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/theme_column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/thememain'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/thememain.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />
        
        
        <!-- blueprint CSS framework -->
	<!--<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />-->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->
	<!--<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />-->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
                <!-- jQuery and jQuery UI (REQUIRED) -->
        <!--<link rel="stylesheet" type="text/css" media="screen" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/smoothness/jquery-ui.css">-->
        
        
        <!--<link rel="stylesheet" type="text/css" media="screen" href="/filemanager/css/jquery-ui-1.10.3.custom.min.css">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

         elFinder CSS (REQUIRED) 
        <link rel="stylesheet" type="text/css" media="screen" href="/filemanager/css/main.css">
        <link rel="stylesheet" type="text/css" media="screen" href="/filemanager/css/elfinder.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="/filemanager/css/theme.css">

         elFinder JS (REQUIRED) 
        <script type="text/javascript" src="/filemanager/js/functions.js"></script>
        <script type="text/javascript" src="/filemanager/js/elfinder.min.js"></script>

         elFinder translation (OPTIONAL) 
        <script type="text/javascript" src="/filemanager/js/i18n/elfinder.ru.js"></script>

         elFinder initialization (REQUIRED) 
        <script>
            $().ready(function() {
                var elf = $('#elfinder').elfinder({
                    url : '/filemanager/php/connector.php'  // connector URL (REQUIRED)
                    // lang: 'ru',             // language (OPTIONAL)
                }).elfinder('instance');
            });
        </script>-->

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
<div id="header">
            <a href="/" title="" id="cloud-logo">Cloud</a>
            
            <div id="logo-claim" style="display:none;"></div>
            
            
            <?php 
//            echo "<pre>";
//                print_r(Yii::app()->user);
//            echo "</pre>";
            ?>
            
            <?php
            if(!Yii::app()->user->isGuest){
                if(Yii::app()->user->role == 1){?>
                    <ul id="settings" class="svg">
                        <span id="expand">
                            <span id="expandDisplayName">admin</span>
                            <img class="svg" src="/filemanager/img/caret.svg" />
                        </span>
                        <div id="expanddiv">
                            <li>
                                <a href="<?php echo $this->createUrl('user/update', array('id'=>Yii::app()->user->id));?>" title="">
                                    <img class="svg" alt="" src="/filemanager/img/personal.svg" />
                                    Account
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->createUrl('user/admin');?>" title="">
                                    <img class="svg" alt="" src="/filemanager/img/users.svg" />
                                    Users
                                </a>
                            </li>
                            <li>
                                <a id="logout" href="<?php echo $this->createUrl('site/logout');?>">
                                    <img class="svg" alt="" src="/filemanager/img/logout.svg" />
                                    LogOut
                                </a>
                            </li>
                        </div>
                    </ul>
                <?php }else{?>
                    <ul id="settings" class="svg">
                        <span id="expand">
                            <span id="expandDisplayName"><?php echo Yii::app()->user->username?></span>
                            <img class="svg" src="/filemanager/img/caret.svg" />
                        </span>
                        <div id="expanddiv">
                            <li>
                                <a href="<?php echo $this->createUrl('user/update', array('id'=>Yii::app()->user->id));?>" title="">
                                    <img class="svg" alt="" src="/filemanager/img/personal.svg" />
                                    Account
                                </a>
                            </li>
                            <li>
                                <a id="logout" href="<?php echo $this->createUrl('site/logout');?>">
                                    <img class="svg" alt="" src="/filemanager/img/logout.svg" />
                                    LogOut
                                </a>
                            </li>
                        </div>
                    </ul>
                <?php }?>
            <?php }?>
        </div>
    
<div class="container" id="page">
    <?php 
//    echo "<pre>";
//        print_r($action);
//    echo "</pre>";
    ?>
    <?php echo $content; ?>
</div>

</body>
</html>